version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tweet_name
      POSTGRES_USER: tweet_user
      POSTGRES_PASSWORD: tweet_password
